image: mhart/alpine-node:10

stages:
  - deploy

before_script:
  - which ssh-agent || ( apk --update add openssh-client )
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - apk add rsync

deploy:
  stage: deploy
  only:
    refs:
      - master
  script:
    - npm i
    - npm run build
    - cp -r php/ dist/
    - echo "rm -rf www/usbani.ru/*" | ssh -oStrictHostKeyChecking=no $USER@$SERVER
    - rsync -h -r -z -e ssh -p -t dist/ $USER@$SERVER:www/usbani.ru/
  tags:
    - web